import { NextResponse } from "next/server";
import { db } from "@/lib/firestore";
import { uploadBufferToGooglePhotos } from "@/lib/googlePhotosServer";

export async function POST(request: Request) {
  try {
    const prediction = await request.json();
    const id = prediction.id;
    
    console.log(`Replicate Webhook for ${id}: ${prediction.status}`);

    if (prediction.status === "succeeded") {
      // Get job context from Firestore
      const docRef = db.collection("replicate_jobs").doc(id);
      const doc = await docRef.get();
      
      if (!doc.exists) {
        console.warn(`No job context found for ${id}`);
        return NextResponse.json({ received: true });
      }
      
      const data = doc.data();
      const { accessToken, prompt, model } = data || {};

      if (accessToken && prediction.output) {
         const outputUrl = Array.isArray(prediction.output) ? prediction.output[0] : prediction.output;
         
         console.log(`Downloading result from ${outputUrl}`);
         
         // Download image
         const res = await fetch(outputUrl);
         const arrayBuffer = await res.arrayBuffer();
         
         // Upload to Google Photos
         const description = `Generated by Replicate (${model})\nPrompt: ${prompt}`;
         await uploadBufferToGooglePhotos(
           accessToken,
           arrayBuffer,
           `replicate_${id}.png`,
           description
         );
         console.log(`Webhook uploaded ${id} to Google Photos`);
         
         // Clean up (optional, or keep for history)
         // await docRef.delete(); 
      }
    }
    
    return NextResponse.json({ received: true });
  } catch (e) {
    console.error("Webhook Error:", e);
    return NextResponse.json({ error: "Internal Error" }, { status: 500 });
  }
}
