import { NextResponse } from "next/server";
import { getAccessToken, uploadBufferToGooglePhotos } from "@/lib/googlePhotosServer";

export async function POST(request: Request) {
  let accessToken;
  try {
    accessToken = await getAccessToken();
  } catch (e: any) {
    // Catch configuration errors
    return NextResponse.json({ error: e.message || "Token refresh error" }, { status: 500 });
  }

  if (!accessToken) {
    return NextResponse.json({ error: "Not authenticated with Google" }, { status: 401 });
  }

  try {
    const formData = await request.formData();
    const file = formData.get("file") as File;
    const description = formData.get("description") as string || "Generated by Flux Web";
    
    if (!file) {
      return NextResponse.json({ error: "No file provided" }, { status: 400 });
    }

    const arrayBuffer = await file.arrayBuffer();
    
    const result = await uploadBufferToGooglePhotos(
      accessToken, 
      arrayBuffer, 
      file.name, 
      description
    );

    return NextResponse.json({ success: true, result });

  } catch (error: any) {
    console.error("Google Photos Upload Error:", error);
    return NextResponse.json({ error: error.message || "Internal Server Error" }, { status: 500 });
  }
}
